In [6]:
# pip install numpy

In [7]:
# a="apple"
# print(a)

In [8]:
# print("shreya")

In [9]:
# import numpy as np
# arr=np.array([10,20,30,40])
# print(arr[2])
# a=np.array([[1,2,3],[4,5,6]])
# print(a[1,2])
# a=np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(a[0,:])
# print(a[:,1])
# arr=np.array([10,20,30,40,50])
# print(arr[arr<15])
# print(arr[[0,2,4]])
# a=np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(a[[1,2],[2,2]])
# matrix=np.array([[10,11,12,13],[14,15,16,17],[18,19,20,21]])
# row_indices=[0,2]
# col_indices=[1,3]
# result=matrix[row_indices,col_indices]
# print(result)

# arithoperation############

# a=np.array([10,20,30])
# b=np.array([1,2,3])
# print(a+b)
# print(a-b)
# print(a/b)
# print(a*b)

# ######median ,mean##########
# arr=np.array([[10,20,30],[30,40,50],[60,70,80]])
# print(np.sum(arr))
# print(np.mean(arr))
# print(np.median(arr))
# print(np.std(arr))
# print(np.var(arr))
# print(np.min(arr))
# print(np.max=np.array([1,2])
# print(np.argmin(arr))
# print(np.argmax(arr))
# print(new_arr.flatten())
# print(new_arr.ravel())
# print(new_arr.transpose())
# a=np.array([1,2])
# b=np.array([3,4])
# print(np.concatenate((a,b)))
# arr=np.array([1,2,3,4,])
# print(np.split(arr,2))
# A=np.array([[1,2],[3,4]])
# B=np.array([[5,6],[7,8]])
# result=np.matmul(A,B)
# print(result)
# v1=np.array([1,2,3])
# v2=np.array([4,5,6])
# print(np.dot(v1,v2))
# A=np.array([[1,2],[3,4]])
# print(np.linalg.inv(A))
# values,vectors=np.linalg.eig(A)
# print(values)


########numpy random
# np.random.rand(3)
# data=[10,20,30,40,50]
# np.random.choice(data,3)
# np.random.normal(loc=0,scale=1,size=5)
# np.random.seed(10)
# print(np.random.seed(3))df.describe()
# print(np.random.rand(3))




import pandas as pd
# print(pd.__version__)

# arr=np.array([5,10,15])
# s=pd.Series(arr)
# print(s)

# print(s)
# data={'name':['Asha','Ravi','john'],'Age':[22,25,23]}
# df=pd.DataFrame(data)
# print(df)


# s=pd.Series([10,20,30])
# print(s)
# df=pd.DataFrame({'A':[10,20,30],'B':[5,6,7]})
# print(df)
# s=pd.Series([10,20,30],index=['a','b','c'])
# print(s)
# print(df.index)
# print(df.columns)


data=[['Anu',22],['Ravi',25],['John',24]]
df=pd.DataFrame(data,columns=['name','age'])
print(df)




# df=pd.read_csv("data.csv")
# print(df.head())

df.info()

# df=pd.read_excel("new.xlsx")
# print(df.head())

   name  age
0   Anu   22
1  Ravi   25
2  John   24
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes

In [10]:
# !pip install --upgrade numpy openpyxl
# !pip uninstall pandas -y
# !pip install --no-cache-dir pandas numpy openpyxl
# import sys
# # print(sys.executable)
# import sys

# !{sys.executable} -m pip uninstall pandas -y


# !{sys.executable} -m pip install --no-cache-dir --force-reinstall pandas numpy openpyxl

!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in /home/novavi/.local/lib/python3.10/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /home/novavi/.local/lib/python3.10/site-packages (from openpyxl) (2.0.0)

In [11]:
import pandas as pd
df=pd.read_excel("new.xlsx")
print(df.head())

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468

In [12]:
pip install --upgrade pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/novavi/.local/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/novavi/.local/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in /home/novavi/.local/lib/python3.10/site-packages (from pandas) (2.2.6)
Requirement already satisfied: pytz>=2020.1 in /home/novavi/.local/lib/python3.10/site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /home/novavi/.local/lib/python3.10/site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /home/novavi/.local/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [13]:
import pandas as pd
df.head
df.head(10)
df.tail()

   0 First Name Last Name  Gender        Country  Age        Date    Id
4  5    Nereida   Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston     Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta      Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean    Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza   Weiland  Female  United States   40  21/05/2015  6548

In [14]:
import numpy as np
e=np.eye(4)
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

In [15]:
# import os
# print(os.getcwd())
# print(os.listdir())
# import os

In [16]:
import sys
print(sys.executable)
print(sys.version)

!ls -la ~/.local/lib/python3.10/site-packages | grep pandas
!ls -la ~/.local/lib/python3.10/site-packages/pandas
rm -rf ~/.local/lib/python3.10/site-packages/pandas
rm -rf ~/.local/lib/python3.10/site-packages/pandas-*.dist-info
python3 -m pip install --no-cache-dir --force-reinstall pandas

SyntaxError: invalid syntax (1477905013.py, line 7)

In [ ]:
import pandas
print(pandas.__version__)

2.3.3

In [ ]:
import pandas as pd
print(pd.__file__)

/home/novavi/.local/lib/python3.10/site-packages/pandas/__init__.py

In [ ]:
import pandas as pd
df=pd.read_excel("new.xlsx")
df.head
df.head(10)
df.tail()


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   0           9 non-null      int64
 1   First Name  9 non-null      object
 2   Last Name   9 non-null      object
 3   Gender      9 non-null      object
 4   Country     9 non-null      object
 5   Age         9 non-null      int64
 6   Date        9 non-null      object
 7   Id          9 non-null      int64
dtypes: int64(3), object(5)
memory usage: 704.0+ bytes

In [ ]:
df.describe()

              0        Age           Id
count  9.000000   9.000000     9.000000
mean   5.000000  35.888889  2989.333333
std    2.738613  13.147666  1511.344517
min    1.000000  24.000000  1562.000000
25%    3.000000  25.000000  2456.000000
50%    5.000000  32.000000  2554.000000
75%    7.000000  40.000000  3549.000000
max    9.000000  58.000000  6548.000000

In [ ]:
df.shape

(9, 8)

In [ ]:
df.columns

Index([0, 'First Name', 'Last Name', 'Gender', 'Country', 'Age', 'Date', 'Id'], dtype='object')

In [ ]:
df.dtypes

0              int64
First Name    object
Last Name     object
Gender        object
Country       object
Age            int64
Date          object
Id             int64
dtype: object

In [ ]:
import pandas as pd
data={"name":["anu","ravi","angel","swa","shrey"],"age":[23,25,34,37,21],"salary":[300,40000,500000,20000,100000],"city":["chennai","ksd","manglore","kannur","bngloere"]}
df=pd.DataFrame(data)
# print(df.loc[2,"age"])
# print(df.loc[0])
# print(df.loc[0:2])
# print(df.loc[1,"name"])
# print(df.loc[0:2,["name","salary"]])
# print(df.loc[0:4,["name","city"]])
# print(df.iloc[0])
# df.iloc[0:3]
# df.iloc[1,2]
# df.iloc[0:3,1:3]print(df.iloc[0])
# df.iloc[0:3]
# df.iloc[1,2]
# df.iloc[0:3,1:3]

# df[df["age"]>23]
# df[df["salary"]>=400000]
# df[(df["age"]>23)&(df["salary"]>30000)]
# df[(df["city"]=="chennai")|(df["city"]=="mumbai")]

df.loc[df["salary"]>30000,"name"]
df.loc[df["age"]>23,["name","salary"]]
df[df["city"].isin(["kannur","chennai"])]
df[df["age"].between(25,37)]
df.query("age>23 and salary>30000")

    name  age  salary      city
1   ravi   25   40000       ksd
2  angel   34  500000  manglore
3    swa   37   20000    kannur

In [ ]:
import pandas as pd
import numpy as np

data = {
    "name": ["anu","anu" ,"pranu", "priya", "None"],
    "age": [23, 23, 22, 23,34],
    "salary": [35000, 35000, None, 4500,6700],
    "city":["delhi","chennai","kerala","dubai","mumbai"],
    "gender":["male","female","male","female","male"]
}
# df.isnull().sum
df = pd.DataFrame(data)

# print(df.isnull())

# print(df.fillna(0))
# print(df["age"].fillna(df["age"].mean(),inplace=True))
# print(df.fillna(method="ffill"))
# print(df.fillna(method="bfill"))

# print(df.duplicated())
# df.drop_duplicates()
# df.drop_duplicates(subset=["name"])
# df.drop_duplicates(keep="first")
# df.drop_duplicates(keep="last")


# df.rename(columns={"salary":"monthly_salary"},inplace=Trudf.replace({"Male":"M","Female":"F"})
# df["city"].replace("delhi","new delhi"),inplace=True)e)
# df.rename(columns={"name":"Empployee_name","age":"emp_age"},inplace=True)
# df.columns=["Emp_name","Emp_age","salary"]
# df.columns=df.columns.str.lower()


# df.replace("chennai","chennaicity",)
# df.replace({"male":"M","female":"F"})
# df["city"].replace("delhi","New Delhi",inplace=True)
# df["salary"].replace([30000,400000],[350000,450000])
# df.replace(r"\$","",regex=True)

/tmp/ipykernel_4864/4206529174.py:37: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["city"].replace("delhi","New Delhi",inplace=True)

0    35000.0
1    35000.0
2        NaN
3     4500.0
4     6700.0
Name: salary, dtype: float64

In [ ]:
data = {
    "name": ["pranu", "pranu", "priya", None],
    "age": [23, np.nan, 22, 23],
    "salary": [35000, 35000, None, 4500]
}
print(df.duplicated(data))
df.drop_duplicates()
df.drop_duplicates(subset=["name"])
df.drop_duplicates(keep="first")
df.drop_duplicates(keep="last")

    name  age   salary       city  gender
0    anu   23  35000.0  New Delhi    male
1    anu   23  35000.0    chennai  female
2  pranu   22      NaN     kerala    male
3  priya   23   4500.0      dubai  female
4   None   34   6700.0     mumbai    male

In [ ]:
# df.dropna()
# df.dropna(axis=1)
# df.dropna(how="all")
# df.dropna(subset=["age"])

    name   age   salary
0    anu  23.0  30000.0
2  priya  22.0      NaN
3   None  23.0   4500.0

In [ ]:
import pandas as pd
# data={
#     "name": ["anu" ,"pranu", "priya", "None"],
#     "age": [23, 23, 22, 23],
#     "salary": [35000, 35000,4500,6700]}
# df=pd.DataFrame(data)
# df["Bonus"]=df["salary"]*0.10 
# print(df)

# df.insert(1,"Department",["HR","IT","FINANCE","IT"])
# print(df)
# df["company"]="ABC Ltd"
# print(df)

# df.sort_values("salary")
# df.sort_values("salary",ascending=False)
# df.sort_values(["Department","salary"],ascending=[True,False])
# df.drop("Bonus",axis=1,inplace=True)
# del df["company"]
# bonus_column=df.pop("Bonus")
# print(df)



# df.sort_values("salary")
# df.sort_values("salary",ascending=False)
# df.sort_values(["Department","salary"],ascending=[True,False])
# df.sort_index()
# df.sort_index(axis=1)

# df["salary"]=df["salary"].apply(lambda x:x+1000)

# def grade_salary(salary):
#     if salary >40000:
#         return "High"
#     else:
#         return "low"
# df["salary_Grade"]=df["salary"].apply(grade_salary)
# print(df)

# df.apply(len)

# df.apply(lambda raw:raw["salary"]*0.05,axis=1)
# print(df)


# df["Department"]=df["Department"].map({"HR":"Human Resources","IT":"information Technology","FINANCE":"finance department"})
# print(df)


# df["Department"].value_counts()

# df["Department"].value_counts(normalize=True)
# df["Department"].value_counts(dropna=False)

             salary
Department
Finance     55000.0
HR          52500.0
IT          55000.0
               sum     mean
            salary   salary
Department
Finance      55000  55000.0
HR          105000  52500.0
IT          110000  55000.0
experience        2        3        4        5        6
Department
Finance         NaN      NaN      NaN      NaN  55000.0
HR              NaN  40000.0      NaN  65000.0      NaN
IT          50000.0      NaN  60000.0      NaN      NaN

In [ ]:

import pandas as pd
data={"Department":["IT","HR","IT","Finance","HR"],
     "employee":["anu","priya","rahul","amit","Neha"],
     "salary":[50000,40000,60000,55000,65000],
     "experience":[2,3,4,6,5]}
df=pd.DataFrame(data)
# print(df)
# print(df.groupby("Department")["salary"].sum())
# df.groupby("Department")["salary"].mean()
# print(df.groupby("Department")["employee"].count())
# print(df.groupby("Department")["salary"].min())
# print(df.groupby("Department")["salary"].max())


# print(df.groupby("Department")["salary"].agg(["sum","mean","min","max"]))

# print(df.groupby(["Department","experience"])["salary"].mean())

# print(df.groupby("Department")["salary"].sum().reset_index())


# print(pd.pivot_table(df,values="salary",index="Department",aggfunc="mean"))

# print(pd.pivot_table(df,values="salary",index="Department",aggfunc=["sum","mean"]))

# print(pd.pivot_table(df,values="salary",index="Department",columns="experience",aggfunc="sum"))

In [ ]:
import pandas as pd
df = pd.read_csv("titanic.csv")
print(df.head())
print(df.info())
print(df.shape)
print(df.columns)
print(df.isnull().sum())
df = df.drop_duplicates()
print(df.shape)
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
df = df.drop("Cabin", axis=1)
print(df.isnull().sum())
df["Sex"] = df["Sex"].map({
    "male":0,
    "female":1
})
df = pd.get_dummies(df, columns=["Embarked"], drop_first=True)
df["FamilySize"] = df["SibSp"] + df["Parch"]
df["FamilySize"] = df["SibSp"] + df["Parch"]
print(df.head())

df.to_csv("cleaned_titanic.csv", index=False)
print("Data Cleaning Completed Successfully!")

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  49 non-null     int64
 1   Survived     49 non-null     int64
 2   Pclass       49 non-null     int64
 3   Name         49 non-null     object
 4   Sex          49 non-null     object
 5   Age          35 non-null     float64
 6   SibSp        49 non-null     int64
 7   Parch        49 non-null     int64
 8   Ticket       49 non-null     object
 9   Fare         49 non-null     float64
 10  Cabin        9 non-null      object
 11  Embarked     49 non-null     object
dtypes: float64(2), int64(5), object(5)
memory usage: 4.7+ KB
None
(49, 12)
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age            14
SibSp           0
Parch           0
Ticket          0
Fare            0
Cabin          40
Embarked        0
dtype: int64
(49, 12)
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0
2                             Heikkinen, Miss. Laina    1  26.0      0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0
4                           Allen, Mr. William Henry    0  35.0      0      0

             Ticket     Fare  Embarked_Q  Embarked_S  FamilySize
0         A/5 21171   7.2500       False        True           1
1          PC 17599  71.2833       False       False           1
2  STON/O2. 3101282   7.9250       False        True           0
3            113803  53.1000       False        True           1
4            373450   8.0500       False        True           0
Data Cleaning Completed Successfully!